DROP DATABASE STUDIO;
CREATE DATABASE STUDIO;
USE STUDIO;

CREATE TABLE IF NOT EXISTS CLIENTES (
`ID` INT NOT NULL AUTO_INCREMENT,
`CPF` VARCHAR(14) NOT NULL,
`NOME` VARCHAR(255) NOT NULL,
`EMAIL` VARCHAR(255) NOT NULL,
`SENHA` VARCHAR(45) NOT NULL,
PRIMARY KEY (`ID`));

CREATE TABLE IF NOT EXISTS AGENDAMENTOS (
`ID` INT NOT NULL AUTO_INCREMENT,
`DATA` DATE NOT NULL,
`HORA` TIME NOT NULL,
`VALOR` FLOAT NOT NULL,
`PROCEDIMENTO` VARCHAR(255) NOT NULL,
`TP_PAGAMENTO` VARCHAR(255) NOT NULL,
`ID_CLIENT` INT NULL,
PRIMARY KEY (`ID`),
INDEX `id_client_idx` (`ID_CLIENT` ASC) VISIBLE,
CONSTRAINT `id_client`
    FOREIGN KEY (`ID_CLIENT`)
    REFERENCES `studio`.`CLIENTES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE VIEW VM_CLIENTES_AGEDAMENTOS as 
    SELECT 
        B.ID,
        B.NOME,
        B.EMAIL,
        B.CPF,
        A.DATA,
        A.HORA,
        A.VALOR,
        A.PROCEDIMENTO,
        A.TP_PAGAMENTO
    FROM AGENDAMENTOS AS A
    JOIN CLIENTES AS B
    ON A.ID_CLIENT = B.ID;
    
    
    
INSERT INTO 
    CLIENTES(CPF,NOME,EMAIL,SENHA)
    VALUES	('12345','MATHEUS','ADM@ADM.COM','123');
    
INSERT INTO 
    AGENDAMENTOS (DATA, HORA, VALOR, PROCEDIMENTO, TP_PAGAMENTO, ID_CLIENT)
    VALUES ('2024-10-27', '14:30:00', 150.00, 'Corte de Cabelo', 'Cartão de Crédito', 1);
                            

select * from CLIENTES;
select * from AGENDAMENTOS;
select * from VM_CLIENTES_AGEDAMENTOS;